services:
  mariadb:
    build: ./database
    container_name: mariadb
    networks:
      - app-network
    volumes:
      - ./database/data:/var/lib/mysql
    env_file:
      - database.env

  metabase:
    image: "metabase/metabase:latest"
    networks:
      - app-network
    env_file:
      - metabase.env
    depends_on:
      - mariadb

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./nginx/hak_assets:/hak_assets
    depends_on:
      - metabase

networks:
  app-network:
    driver: bridge